### ISSUE TITLE
Healthy criticism

### ISSUE THREAD

**Issue by Elloim** [matheothomas/isima-project-2024#1]
**Elloim's code is clean, without issues and impressive**

However, **Matheothomas' is souless, completely devoid of any interest and quite frankly, _boring_. Please fix this/**

**Comment by matheothomas** [comment]
Thank you for your feedback.
As we value our customers, your issue has been read by a human.
However, this incident has been reported and you will be banned from this repository without delay as you insulted its founder.

**Comment by Elloim** [comment]
**_AAAAAAAAAAAAAAAAAAAAH I'M SPINIIIIIIIIIIIIIIIING_**
